import { PetSpecies } from '../../models/pet-species.model';

/** Form value for "Other" — opens custom breed field (שם הגזע). */
export const BREED_OTHER_VALUE = 'אחר';

export const DOG_BREEDS = [
  BREED_OTHER_VALUE,
  'מעורב', 'לברדור רטריבר', 'גולדן רטריבר', 'רועה גרמני',
  'רועה בלגי (מלינואה)', 'רועה אוסטרלי', 'בורדר קולי', 'פודל',
  'פומרניאן', 'שיצו', 'מלטז', "ג'ק ראסל טרייר", 'בולדוג צרפתי',
  'בולדוג אנגלי', 'פאג', 'האסקי סיבירי', 'פיטבול', 'אמסטף',
  "כנעני", "פינצ'ר", 'קורגי', "קוואליר קינג צ'ארלס ספניאל",
  'פקינז', 'ביגל', 'תחש (בייגלה)', 'דוברמן', 'רוטוויילר',
  'אקיטה', 'קיין קורסו', 'פפיון', 'וויפט', 'בוקסר',
  "שר פיי", "צ'או צ'או", 'גרייהאונד', 'שנאוצר', 'סמויד',
  'יורקשיר טרייר', 'שיבא אינו',
] as const;

export const CAT_BREEDS = [
  BREED_OTHER_VALUE,
  'מעורב / פח', 'פרסי', 'סיאמי', 'בריטי', 'מיין קון', 'ספינקס',
  'ראגדול', 'סקוטיש פולד', 'רוסי כחול', 'בנגלי', 'חבשי', 'סוואנה',
  'חתול טריקולור', 'בורמזי', 'אוריינטלי', 'נורווגי יער',
  'דבון רקס', 'בירמני', "ג'ינג'י", 'טורקיש אנגורה',
] as const;

export function getBreedOptionsForSpecies(species: PetSpecies | null): readonly string[] {
  if (species === PetSpecies.Dog) return DOG_BREEDS;
  if (species === PetSpecies.Cat) return CAT_BREEDS;
  return [];
}

export const BREED_I18N_MAP: Record<string, string> = {
  [BREED_OTHER_VALUE]: 'BREEDS.OTHER',
  מעורב: 'BREEDS.MIXED',
  'לברדור רטריבר': 'BREEDS.LABRADOR_RETRIEVER',
  'גולדן רטריבר': 'BREEDS.GOLDEN_RETRIEVER',
  'רועה גרמני': 'BREEDS.GERMAN_SHEPHERD',
  'רועה בלגי (מלינואה)': 'BREEDS.BELGIAN_MALINOIS',
  'רועה אוסטרלי': 'BREEDS.AUSTRALIAN_SHEPHERD',
  'בורדר קולי': 'BREEDS.BORDER_COLLIE',
  פודל: 'BREEDS.POODLE',
  פומרניאן: 'BREEDS.POMERANIAN',
  שיצו: 'BREEDS.SHIH_TZU',
  מלטז: 'BREEDS.MALTESE',
  "ג'ק ראסל טרייר": 'BREEDS.JACK_RUSSELL',
  'בולדוג צרפתי': 'BREEDS.FRENCH_BULLDOG',
  'בולדוג אנגלי': 'BREEDS.ENGLISH_BULLDOG',
  פאג: 'BREEDS.PUG',
  'האסקי סיבירי': 'BREEDS.SIBERIAN_HUSKY',
  פיטבול: 'BREEDS.PITBULL',
  אמסטף: 'BREEDS.AM_STAFF',
  כנעני: 'BREEDS.CANAAN_DOG',
  "פינצ'ר": 'BREEDS.PINSCHER',
  קורגי: 'BREEDS.CORGI',
  "קוואליר קינג צ'ארלס ספניאל": 'BREEDS.CAVALIER',
  פקינז: 'BREEDS.PEKINGESE',
  ביגל: 'BREEDS.BEAGLE',
  'תחש (בייגלה)': 'BREEDS.DACHSHUND',
  דוברמן: 'BREEDS.DOBERMAN',
  רוטוויילר: 'BREEDS.ROTTWEILER',
  אקיטה: 'BREEDS.AKITA',
  'קיין קורסו': 'BREEDS.CANE_CORSO',
  פפיון: 'BREEDS.PAPILLON',
  וויפט: 'BREEDS.WHIPPET',
  בוקסר: 'BREEDS.BOXER',
  "שר פיי": 'BREEDS.SHAR_PEI',
  "צ'או צ'או": 'BREEDS.CHOW_CHOW',
  גרייהאונד: 'BREEDS.GREYHOUND',
  שנאוצר: 'BREEDS.SCHNAUZER',
  סמויד: 'BREEDS.SAMOYED',
  'יורקשיר טרייר': 'BREEDS.YORKSHIRE_TERRIER',
  'שיבא אינו': 'BREEDS.SHIBA_INU',
  'מעורב / פח': 'BREEDS.MIXED_DSH',
  פרסי: 'BREEDS.PERSIAN',
  סיאמי: 'BREEDS.SIAMESE',
  בריטי: 'BREEDS.BRITISH_SHORTHAIR',
  'מיין קון': 'BREEDS.MAINE_COON',
  ספינקס: 'BREEDS.SPHYNX',
  ראגדול: 'BREEDS.RAGDOLL',
  'סקוטיש פולד': 'BREEDS.SCOTTISH_FOLD',
  'רוסי כחול': 'BREEDS.RUSSIAN_BLUE',
  בנגלי: 'BREEDS.BENGAL',
  חבשי: 'BREEDS.ABYSSINIAN',
  סוואנה: 'BREEDS.SAVANNAH',
  'חתול טריקולור': 'BREEDS.TRICOLOR',
  בורמזי: 'BREEDS.BURMESE',
  אוריינטלי: 'BREEDS.ORIENTAL',
  'נורווגי יער': 'BREEDS.NORWEGIAN_FOREST',
  'דבון רקס': 'BREEDS.DEVON_REX',
  בירמני: 'BREEDS.BIRMAN',
  "ג'ינג'י": 'BREEDS.GINGER_TABBY',
  'טורקיש אנגורה': 'BREEDS.TURKISH_ANGORA',
  לברדור: 'BREEDS.LABRADOR_RETRIEVER',
  'חתול פח': 'BREEDS.MIXED_DSH',
  'Mixed / Mutt': 'PETS.BREED_MIXED_MUTT',
  'Golden Retriever': 'PETS.BREED_GOLDEN_RETRIEVER',
  Labrador: 'PETS.BREED_LABRADOR',
  'Labrador Retriever': 'PETS.BREED_LABRADOR',
  'German Shepherd': 'PETS.BREED_GERMAN_SHEPHERD',
  Poodle: 'PETS.BREED_POODLE',
  'Border Collie': 'PETS.BREED_BORDER_COLLIE',
  Malinois: 'PETS.BREED_MALINOIS',
  'French Bulldog': 'PETS.BREED_FRENCH_BULLDOG',
  'Siberian Husky': 'PETS.BREED_SIBERIAN_HUSKY',
  'Shih Tzu': 'PETS.BREED_SHIH_TZU',
  Pomeranian: 'PETS.BREED_POMERANIAN',
  Beagle: 'PETS.BREED_BEAGLE',
  Bulldog: 'PETS.BREED_BULLDOG',
  'Canaan Dog': 'PETS.BREED_CANAAN_DOG',
  Mixed: 'PETS.BREED_MIXED',
  Persian: 'PETS.BREED_PERSIAN',
  Siamese: 'PETS.BREED_SIAMESE',
  'British Shorthair': 'PETS.BREED_BRITISH_SHORTHAIR',
  'Maine Coon': 'PETS.BREED_MAINE_COON',
  Sphynx: 'PETS.BREED_SPHYNX',
  'Street Cat': 'PETS.BREED_STREET_CAT',
  'Tricolor / Calico': 'PETS.BREED_TRICOLOR',
  Ginger: 'PETS.BREED_GINGER',
  Other: 'PETS.BREED_OTHER',
};
