import { useMemo } from "react";
import { StyleSheet } from "react-native";
import { useTheme } from "../../theme/ThemeContext";

export const getStyles = (colors: any) =>
  StyleSheet.create({
    categoryTabsScroll: {
      backgroundColor: colors.surface,
      marginTop: 0,
      flexShrink: 1,
    },
    topTabsContent: {
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 6,
      gap: 10,
      alignItems: "flex-start",
    },
    topTab: {
      alignItems: "center",
      justifyContent: "flex-start",
      minWidth: 76,
      flexShrink: 0,
      paddingVertical: 0,
    },
    topTabCircleWrap: {
      width: 76,
      height: 76,
      position: "relative",
      alignItems: "center",
      justifyContent: "center",
    },
    topTabBadge: {
      position: "absolute",
      top: -2,
      minWidth: 18,
      height: 18,
      paddingHorizontal: 4,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      zIndex: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.12,
      shadowRadius: 2,
      elevation: 3,
    },
    topTabBadgeAlert: {
      backgroundColor: colors.warning,
    },
    topTabBadgeText: {
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: -0.2,
    },
    topTabCircle: {
      width: 76,
      height: 76,
      borderRadius: 38,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#06256f",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    topTabCircleActive: {
      backgroundColor: colors.text,
      borderColor: colors.text,
    },
    topTabCircleInactive: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    topTabText: {
      marginTop: 8,
      fontSize: 13,
      fontWeight: "700",
      color: colors.textSecondary,
      textAlign: "center",
      lineHeight: 16,
      maxWidth: 92,
    },
    topTabTextActive: {
      color: "#06256F",
      fontWeight: "800",
    },
    searchCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: colors.surface,
      borderRadius: 16,
      marginHorizontal: 16,
      marginTop: 10,
      paddingHorizontal: 14,
      minHeight: 54,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.text,
    },
    filterContent: {
      paddingHorizontal: 16,
      paddingTop: 10,
      gap: 8,
      paddingBottom: 2,
    },
    chip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      minHeight: 36,
    },
    chipActive: { backgroundColor: colors.text, borderColor: colors.text },
    chipInactive: { backgroundColor: colors.surface, borderColor: colors.border },
    chipText: { fontSize: 12, fontWeight: "800" },
    chipTextActive: { color: colors.textInverse },
    chipTextInactive: { color: colors.textSecondary },
    demoBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginHorizontal: 16,
      marginTop: 10,
      padding: 10,
      borderRadius: 14,
      backgroundColor: colors.primaryLight,
    },
    demoBannerText: { flex: 1, color: colors.primary, fontSize: 12, fontWeight: "700" },
    pillsRow: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 4,
      gap: 10,
    },
    pill: { paddingHorizontal: 20, paddingVertical: 8, borderRadius: 20 },
    pillActive: { backgroundColor: colors.text },
    pillInactive: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    pillText: { fontSize: 14, fontWeight: "600" },
    pillTextActive: { color: colors.textInverse },
    pillTextInactive: { color: colors.textSecondary },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      marginHorizontal: 16,
      marginTop: 10,
      padding: 14,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    cardRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    avatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.text,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: { color: colors.textInverse, fontSize: 14, fontWeight: "700" },
    authorRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      flexWrap: "wrap",
    },
    authorName: { fontSize: 15, fontWeight: "700", color: colors.text },
    providerBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      backgroundColor: colors.text,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 8,
    },
    providerBadgeText: { color: colors.textInverse, fontSize: 10, fontWeight: "700" },
    sosBadge: {
      backgroundColor: "#dc2626",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 8,
    },
    kindBadge: {
      backgroundColor: colors.primaryLight,
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 999,
    },
    kindBadgeText: { color: colors.text, fontSize: 10, fontWeight: "800" },
    timeText: { fontSize: 12, color: colors.textMuted, marginTop: 1 },
    contentText: { fontSize: 15, color: colors.text, lineHeight: 23, marginTop: 12 },
    dogMiniCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      padding: 10,
      borderRadius: 14,
      backgroundColor: colors.surfaceTertiary,
      marginTop: 12,
    },
    dogAvatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.text,
      alignItems: "center",
      justifyContent: "center",
    },
    dogName: { color: colors.text, fontSize: 14, fontWeight: "800" },
    dogSubtle: { color: colors.textMuted, fontSize: 12 },
    dogProfileRail: {
      gap: 12,
      paddingTop: 12,
      paddingBottom: 2,
    },
    dogProfileCard: {
      width: 154,
      padding: 12,
      borderRadius: 18,
      backgroundColor: colors.surfaceTertiary,
      borderWidth: 1,
      borderColor: colors.borderLight,
      alignItems: "center",
    },
    dogProfileAvatar: {
      width: 78,
      height: 78,
      borderRadius: 39,
      overflow: "hidden",
      backgroundColor: colors.text,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    dogProfileName: { color: colors.text, fontSize: 15, fontWeight: "900", textAlign: "center", lineHeight: 19 },
    dogProfileSub: { color: colors.textMuted, fontSize: 12, marginTop: 3, textAlign: "center", lineHeight: 17 },
    postImage: {
      width: "100%",
      aspectRatio: 4 / 3,
      borderRadius: 12,
      marginTop: 12,
      backgroundColor: colors.surfaceSecondary,
    },
    composerThumbnail: {
      width: "100%",
      aspectRatio: 4 / 3,
      borderRadius: 12,
      backgroundColor: colors.surfaceSecondary,
    },
    thumbnailRemoveBtn: {
      position: "absolute",
      top: 8,
      right: 8,
    },
    pickerIconBtn: {
      padding: 6,
    },
    imagePlaceholder: {
      height: 180,
      borderRadius: 12,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 12,
    },
    playdateInline: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 12,
      borderRadius: 16,
      backgroundColor: colors.primaryLight,
      marginTop: 12,
    },
    inlineTitle: { fontSize: 14, fontWeight: "900", color: colors.text },
    inlineSub: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
    menu: {
      alignSelf: "flex-end",
      marginTop: 10,
      borderRadius: 14,
      backgroundColor: colors.surfaceTertiary,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    menuText: { color: colors.textSecondary, fontSize: 13, fontWeight: "700" },
    actionBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 20,
      marginTop: 14,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      flexWrap: "wrap",
    },
    actionBtn: { flexDirection: "row", alignItems: "center", gap: 6 },
    actionText: { fontSize: 13, fontWeight: "600", color: colors.textSecondary },
    commentSection: {
      backgroundColor: colors.surfaceTertiary,
      borderRadius: 12,
      marginTop: 12,
      padding: 12,
    },
    commentItem: { flexDirection: "row", gap: 8, marginBottom: 10 },
    commentAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.textMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    commentAvatarText: { color: colors.textInverse, fontSize: 10, fontWeight: "700" },
    commentHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    commentAuthor: { fontSize: 13, fontWeight: "700", color: colors.text },
    commentTime: { fontSize: 11, color: colors.textMuted },
    commentContent: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
      marginTop: 2,
    },
    commentInputRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginTop: 8,
    },
    commentInput: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 8,
      fontSize: 13,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.border,
    },
    commentSendBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.text,
      alignItems: "center",
      justifyContent: "center",
    },
    composerClosed: { flexDirection: "row", alignItems: "center", gap: 12 },
    composerAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.text,
      alignItems: "center",
      justifyContent: "center",
    },
    composerPlaceholder: { flex: 1, fontSize: 15, color: colors.textMuted },
    composerInput: {
      fontSize: 15,
      color: colors.text,
      minHeight: 80,
      textAlignVertical: "top",
      lineHeight: 22,
    },
    composerActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      gap: 12,
      marginTop: 12,
    },
    composerCancel: { paddingHorizontal: 16, paddingVertical: 10 },
    composerCancelText: { fontSize: 14, fontWeight: "600", color: colors.textSecondary },
    publishBtn: {
      backgroundColor: colors.text,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 12,
      minWidth: 90,
      alignItems: "center",
    },
    publishText: { color: colors.textInverse, fontSize: 14, fontWeight: "700" },
    quickActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flexWrap: "wrap",
    },
    quickActionPrimary: {
      flex: 1,
      minWidth: 140,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.text,
      paddingVertical: 12,
      minHeight: 48,
      borderRadius: 14,
    },
    quickActionPrimaryText: { color: colors.textInverse, fontSize: 14, fontWeight: "900" },
    quickActionSecondary: {
      flex: 1,
      minWidth: 140,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.primaryLight,
      paddingVertical: 12,
      minHeight: 48,
      borderRadius: 14,
    },
    quickActionSecondaryText: { color: colors.text, fontSize: 14, fontWeight: "900" },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 4,
      flexWrap: "wrap",
    },
    sectionTitle: { color: colors.text, fontSize: 22, fontWeight: "900" },
    sectionSubtitle: { color: colors.textSecondary, fontSize: 13, lineHeight: 18, marginTop: 2 },
    sectionCardTitle: { color: colors.text, fontSize: 16, fontWeight: "900" },
    sectionCardSub: { color: colors.textSecondary, fontSize: 12, marginTop: 3 },
    iconBubble: {
      width: 42,
      height: 42,
      borderRadius: 15,
      backgroundColor: colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    metaWrap: {
      flexDirection: "row",
      gap: 7,
      flexWrap: "wrap",
      marginTop: 12,
    },
    metaPill: {
      overflow: "hidden",
      borderRadius: 999,
      backgroundColor: colors.surfaceSecondary,
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "800",
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    primarySmallBtn: {
      backgroundColor: colors.text,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 12,
      alignSelf: "flex-start",
      minHeight: 38,
      justifyContent: "center",
    },
    primarySmallText: { color: colors.textInverse, fontSize: 12, fontWeight: "900" },
    smallOutlineBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 12,
      alignSelf: "flex-start",
      minHeight: 38,
      justifyContent: "center",
    },
    smallOutlineText: { color: colors.text, fontSize: 12, fontWeight: "800" },
    rsvpButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.surfaceSecondary,
    },
    rsvpButtonActive: { backgroundColor: colors.text },
    rsvpText: { color: colors.textSecondary, fontSize: 12, fontWeight: "800" },
    rsvpTextActive: { color: colors.textInverse },
    liveBeaconRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingTop: 12,
    },
    liveDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.success,
    },
    emptyInline: { color: colors.textMuted, fontSize: 13, lineHeight: 19, marginTop: 10 },
    modalRoot: {
      flex: 1,
      justifyContent: "flex-end",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "flex-end",
    },
    modalBackdropFill: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
    },
    keyboardSheet: { flex: 1, justifyContent: "flex-end" },
    detailSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 26,
      borderTopRightRadius: 26,
      padding: 20,
      paddingBottom: 34,
      maxHeight: "88%",
    },
    handle: {
      width: 42,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: "center",
      marginBottom: 16,
    },
    modalTitle: { color: colors.text, fontSize: 22, fontWeight: "900", marginBottom: 12 },
    label: { color: colors.textSecondary, fontSize: 13, fontWeight: "800", marginTop: 12, marginBottom: 8 },
    input: {
      backgroundColor: colors.surfaceTertiary,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: colors.text,
      fontSize: 15,
      marginTop: 10,
    },
    textArea: { minHeight: 96, textAlignVertical: "top" },
    modalChipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    modalChip: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.surface,
    },
    modalChipActive: { backgroundColor: colors.text, borderColor: colors.text },
    modalChipText: { color: colors.textSecondary, fontSize: 12, fontWeight: "800" },
    modalChipTextActive: { color: colors.textInverse },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      gap: 10,
      marginTop: 14,
    },
    mediaRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 10 },
    twoCol: { flexDirection: "row", gap: 10 },
    colInput: { flex: 1 },
    checkRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 14 },
    checkText: { color: colors.text, fontSize: 14, fontWeight: "700" },
    mapPlaceholder: {
      height: 140,
      borderRadius: 18,
      backgroundColor: colors.surfaceTertiary,
      overflow: "hidden",
      marginTop: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    largeDogAvatar: {
      width: 96,
      height: 96,
      borderRadius: 48,
      overflow: "hidden",
      backgroundColor: colors.text,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
      marginBottom: 12,
    },
    primaryBtn: {
      backgroundColor: colors.text,
      paddingVertical: 14,
      borderRadius: 14,
      alignItems: "center",
      marginTop: 14,
    },
    primaryBtnText: { color: colors.textInverse, fontSize: 15, fontWeight: "900" },
    emptyContainer: {
      alignItems: "center",
      paddingTop: 60,
      paddingHorizontal: 32,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text,
      textAlign: "center",
      marginTop: 16,
    },
    emptySubtitle: {
      fontSize: 14,
      color: colors.textMuted,
      textAlign: "center",
      marginTop: 6,
    },
    loadMoreBtn: {
      alignSelf: "center",
      backgroundColor: colors.surface,
      paddingHorizontal: 28,
      paddingVertical: 12,
      borderRadius: 24,
      marginVertical: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    loadMoreText: { fontSize: 14, fontWeight: "600", color: colors.text },
    loadingCenter: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    sosMarkFoundWrap: {
      marginTop: 14,
      alignSelf: "stretch",
    },
    sosMarkFoundFullBtn: {
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: "#22c55e",
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 12,
      minHeight: 52,
    },
    sosMarkFoundFullBtnDisabled: {
      opacity: 0.65,
    },
    sosMarkFoundFullBtnText: {
      color: "#fff",
      fontSize: 17,
      fontWeight: "800",
      flexShrink: 1,
    },
  });

export function useCommunityStyles() {
  const { colors } = useTheme();
  return useMemo(() => getStyles(colors), [colors]);
}
