/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        cream: "#FAF9F6",
        navy: "#00236F",
        // STITCH / Material palette (auth & extended UI)
        background: "#faf9f6",
        "on-background": "#1a1c1a",
        "surface-dim": "#dbdad7",
        surface: "#faf9f6",
        "surface-bright": "#faf9f6",
        "surface-variant": "#e3e2e0",
        "surface-container": "#efeeeb",
        "surface-container-low": "#f4f3f1",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#444651",
        outline: "#757682",
        "outline-variant": "#c5c5d3",
        primary: "#00236f",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a8a",
        "on-primary-container": "#90a8ff",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#264191",
        "inverse-primary": "#b6c4ff",
        secondary: "#00687a",
        "on-secondary": "#ffffff",
        "secondary-container": "#57dffe",
        "on-secondary-container": "#006172",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        tertiary: "#4b1c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6e2c00",
        "on-tertiary-container": "#f39461",
        "tertiary-fixed": "#ffdbcb",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-fixed-variant": "#773205",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-tint": "#4059aa",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
      },
      fontFamily: {
        headline: ["Manrope", "Inter", "Segoe UI", "system-ui", "sans-serif"],
        body: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
        label: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        "shell-header": "0 24px 48px -12px rgba(30, 58, 138, 0.08)",
        "shell-nav": "0 24px 48px -12px rgba(30, 58, 138, 0.12)",
      },
      scale: {
        98: "0.98",
      },
    },
  },
  plugins: [],
}
